# Source-grounded study notes. These are explanations, not a new app test run.
COMMON = [
('Commands, events and safe changes', 'lib/server/commands.ts; lib/server/workflow.ts; supabase/migrations/202609260001_workflow.sql', [
('What actually happens when someone presses Send?', 'The screen requests an action; the server decides which events may be recorded.', 'The route authenticates the request and requires a run ID. The command executor reads the current snapshot, validates the complete transition, plans the permitted events and commits against the expected run/revision. The database locks the active-run pointer and writes the batch atomically. Other screens derive their view from the committed history. A client cannot submit an arbitrary new patient narrative or bypass the server by changing the button label.', 'ELI5: asking to add a line to the notebook is different from an accepted line.'),
('What happens if two people act at once or press twice?', 'The server checks state again and uses database identity/revision guards to avoid accepting incompatible plans.', 'Event identity is scoped by run and script ID. A repeat of an already-completed action can become a no-op; even that no-op checks run identity under the lock. A revision conflict causes a fresh snapshot and replan, for at most three attempts. The classifier result is cached during those retries. This is bounded conflict handling, not a guarantee that every command always succeeds or that every external service executes exactly once.', 'Example: two screens racing the same action must not manufacture two copies of its event.'),
('What does reset mean, and why keep old runs?', 'Reset switches the active run to a new identity; old committed history can still be read for replay.', 'The same fictional case IDs recur in demos, so case ID alone is insufficient. A command for an old run is rejected rather than applied to the new one. Screens discard stale responses using run/revision and local generation checks. Coordinator links and messages are run-scoped, so reset requires a fresh interactive approval. Reset is a coordinated shared-demo operation; it does not recall a notification already in flight.', 'ELI5: the notebook session changes, even if the names on the next page look familiar.')
]),
('Synchronization, storage and access', 'lib/realtime.ts; lib/server/command-http.ts; lib/server/demo-session.ts; supabase/migrations', [
('Is this Supabase Realtime?', 'No. Screens use authenticated HTTP polling, normally every 1.5 seconds.', 'The EventSource interface name is an internal abstraction, not browser Server-Sent Events. The adapter asks the Next server for snapshots and uses an ETag based on run and revision; unchanged state can return 304. It refuses outdated revisions and responses from an obsolete local generation. Polling makes this demo straightforward, but creates repeated requests and is not a zero-latency guarantee. Subscription design and scale would need a separate evaluation.', 'Say: Supabase stores state; authenticated polling synchronizes the screens.'),
('What is shared and what is local?', 'Live workflow history, coordinator relationships and approved patient messages are shared; contact marks stay on the browser.', 'Supabase holds the synthetic catalog, runs, events, notification outbox and coordinator/message records. Tiger stores a reduced analytics projection. Reached patient and Left message are local reminders, not calls or messages, and do not synchronize between devices. Mock mode also keeps local simulation behavior. A reliable explanation names the source of each item rather than saying that every visible control is shared live state.', 'Example: a message approval appears on another signed-in session; a local contact mark does not.'),
('Does login make this a production healthcare system?', 'It protects the private demo, but it is not real patient, practice or buyer authorization.', 'The demo uses a signed HttpOnly session cookie with a seven-day lifetime, SameSite restrictions and Secure behavior on HTTPS/production; server tools can use bearer authentication. Mutating session requests enforce same-origin checks. Browser database roles lack direct access to the protected tables/functions; the backend holds service credentials. These controls do not establish tenant isolation, patient consent, professional identity, a compliance assessment or a production audit/retention program.', 'Explain the protection that exists, then name the missing identity boundary.')
]),
('Verified labels: what the claim means', 'lib/server/label.ts; lib/server/labels; scripts/labels; data/labels/drug_otezla', [
('What exactly is verified about the Otezla label?', 'The application serves cached text verified against saved DailyMed source sections and drug identity evidence.', 'This is a source-verification pipeline, not generated medical advice. Saved artifacts carry provenance and a verification contract; the offline verifier checks source-derived text and the published fixture. The rendered Otezla sections were compared with that fixture in the recorded hosted audit. Explain literal extracted text accurately: byte-exact in this project does not mean the visual web page is identical to raw source XML, or that all UI statements are FDA-verified.', 'ELI5: we keep both the copied text and the receipt showing what it was copied from.'),
('Why is a hash useful, and what does it not prove?', 'A hash helps detect changes; provenance and identity checks explain what the source is.', 'If content changes, its digest should no longer match the expected artifact. A digest alone cannot tell whether the original document was authoritative, current or even the intended drug. That is why source identity, version information, extraction rules and the published artifact must be checked together. The recorded verifier rejects a one-character change. Avoid describing hashing as encryption, regulatory approval or proof that a document is always current.', 'If asked about freshness: this is a verified cached snapshot, not a runtime DailyMed fetch.'),
('What about Humira and other medications?', 'Both Otezla and Humira now have verified cached DailyMed label artifacts in merged source.', 'Humira was added with its own saved DailyMed/RxNorm evidence, boxed warning, volume-aware identity checks and nested KIT handling. Its branch-local endpoint/render checks and 728 tests in 54 files are recorded in Minh’s sign-off; a new deployed Humira check was not run for this PDF. Further drugs still need independent verification. A prepared before-visit card is also separate from label support: it needs a scripted/offline event and has no automatic live appointment trigger in the inspected planner.', 'Two verified drugs do not imply universal drug coverage. Humira deployment must be checked separately from branch-local evidence.')
]),
('Gemini and the rulebook', 'lib/server/classify.ts; lib/server/classifier; lib/server/commands.ts; lib/server/router.ts', [
('Why use Gemini if the rules choose the action?', 'Gemini handles language interpretation; the deterministic router controls the administrative choice.', 'The classifier maps a fictional pharmacy/hub note into one permitted reason or null. The planner validates the complete command batch before sending the supported source note for classification. The live result is supplied as trusted server context, not accepted from the browser. Free-form generated text is not saved as patient narrative. Separating these jobs keeps a model response from directly choosing a card, sample or treatment.', 'ELI5: the reader sorts the note into a labeled box; the rulebook decides which task is allowed.'),
('What if Gemini is wrong, slow or unavailable?', 'Invalid, unknown, failed or timed-out responses become null; the system does not restore a scripted answer in live mode.', 'The facade rejects blank or over-140-code-point notes and applies a four-second deadline, including transports that ignore cancellation. The allowed output parser constrains format. A null reason creates no reason-triggered doctor alert, while Patient Details and access support remain available. Price refusal also needs an existing recorded quote. A valid but wrong allowed reason is still possible; real-world accuracy would require labeled evaluation beyond the few demo fixtures.', 'One passing smoke test proves a request path worked, not clinical accuracy or a latency guarantee.'),
('How are card and sample actions constrained?', 'The router requires a recognized reason, a matching rule and explicit eligibility flags.', 'A copay-card result requires the matching commercial-insurance rule and copayCardEligible exactly true. The bridge-sample path requires its own eligible flag and matching row. Missing, unknown or unmatched inputs fall back to ACCESS_SUPPORT. This is the demo’s administrative routing contract. It does not verify an actual patient’s program eligibility, adjudicate coverage or submit a request to a real partner.', 'A cost problem alone never proves someone qualifies for a manufacturer card.')
]),
('Tiger: turning history into numbers', 'lib/server/analytics-runtime.ts; lib/server/analytics/project.ts; lib/server/analytics/summary.ts', [
('What data reaches Tiger, and why keep a separate projection?', 'Only allowlisted metric events reach Tiger; the practice-side workflow remains the source of history.', 'Replay reads committed events for a specified run, projects supported events and writes the reduced metric batch. Persisted fields include run/script identifiers, a keyed case hash, time, metric kind and allowed reason. Names, raw notes, drug labels, insurance details and wrist text are not part of this analytics projection. This makes the reporting contract inspectable, but a pseudonymous metric store is not the same as a complete buyer-access or privacy system.', 'ELI5: the scoreboard receives the points it needs, not a copy of the whole notebook.'),
('What do first fills and time to first fill mean here?', 'A case counts when it has a qualifying pharmacy confirmation at or after its earliest prescription.', 'For each case, the summary finds the earliest prescription and earliest qualifying later-or-equal fill, then takes the median elapsed time across filled cases. Unfilled cases are excluded, so this is not everyone’s waiting time. Empty results have a null median. The legacy response field recovered means a confirmed fill, not clinical recovery. Reason tallies use each case’s latest non-null reason, including cases later filled; they are not necessarily the unresolved queue distribution.', 'Resource acknowledgment, message acknowledgment and a price change are not qualifying fills.'),
('What do the displayed demo numbers actually establish?', 'They establish that the reporting path computes the expected result from synthetic history.', 'The recorded deployed audit returned 8 seeded fills, a 60-second median and three reason counts of 2; reset returned 0 fills, a null median and empty reasons. Separate retained-run replay and duplicate checks passed. These numbers are not a patient study, conversion lift, time saved by staff or proof that FirstDose caused a fill. The implementation queries a hypertable directly; it does not use a continuous aggregate.', 'Lead with the source and cohort before interpreting any dashboard number.')
]),
('Replay, freshness and privacy limits', 'lib/server/replay-followup.ts; lib/server/analytics-http.ts; lib/server/analytics/store.ts; lib/realtime.ts', [
('How can replay avoid counting the same event twice?', 'Stable event identity and immutable payload checks distinguish a repeat from a conflicting rewrite.', 'The analytics writer uses ledger/transaction logic around event identity. Identical retries are safe; an event with the same identity but changed canonical contents is a conflict, not a silent update. Hosted evidence includes concurrent duplicate replay with unchanged counts. This lets the summary catch up from retained history after a missed background attempt. It is not a promise that any arbitrary payload can be replayed or that a failed provider call succeeded.', 'ELI5: the same receipt is counted once; changing its amount under the same receipt number is an error.'),
('How do you stop an old summary appearing after reset?', 'Both server and browser require the summary to match the requested run and revision.', 'The server checks the active checkpoint before reading retained history, after the read, after replay and after querying. It uses a cloned history for the replay. The response carries matching run/revision headers; the client also compares its current generation and revision. A stale checkpoint returns 409, invalid query parameters 400, unavailable/configuration failure 503, and missing authorization 401. Failed replay is not disguised as a successful zero-filled summary.', 'A genuine empty result and an unavailable result are different states.'),
('Are hashed analytics anonymous? Who else receives data?', 'The hashes are pseudonymous; the complete data flow includes external providers.', 'Tiger receives a keyed case identifier rather than the raw case identity through the projector. A stable HMAC key is needed for consistent replay; changing it conflicts with existing immutable projections. The shared app session is not a separate pharma/buyer permission system. ntfy receives fictional alert text, Gemini receives the supported fictional note, and optional xAI receives the recorded command. The prototype does not control every provider’s retention policy or establish real-patient compliance.', 'Do not say that names can never leave the practice: the notification and optional voice paths need their own explanation.')
]),
('Watch, voice and patient audio', 'lib/server/notification-worker.ts; lib/server/voice.ts; app/(screens)/doctor/_components/VoiceHandoff.tsx; components/PatientMessage.tsx', [
('Can you guarantee exactly one watch buzz?', 'No. We guard duplicate sends, but server acceptance and physical receipt are different events.', 'Workflow commits queue the relevant notification. A worker claims an outbox row before publishing and records accepted or unknown. It attempts at most two sends per invocation, and claimed/unknown rows are not automatically reclaimed after ambiguous failures. That favors avoiding repeated sends, with a possible missed delivery if the process fails at the wrong time. A reset cannot recall an in-flight request. Earlier Garmin receipt is recorded; the intended physical presentation run still needs its own proof.', 'A browser wrist mirror shows intended text; it does not establish that a watch received it.'),
('What does Grok do, and what is still incomplete?', 'It transcribes the supported spoken handoff and proposes a case for human confirmation.', 'The endpoint accepts bounded audio, calls xAI and parses a narrow command rather than allowing arbitrary tool use. It does not itself write a handoff. The UI converts unsupported browser recording formats when needed. A merged pre-confirm run check rejects proposals when it detects a different active run, but run capture happens after recording and only the case ID is handed onward. Complete recording-through-approval reset safety and human-device acceptance remain unverified; keep the button path available.', 'A successful synthetic-audio provider test does not prove microphone capture or a full confirmed handoff.'),
('Are the patient messages generated live by AI?', 'No. The eligible Otezla path uses approved templates and pre-generated English/Spanish audio.', 'After the scripted card-resend fix, the coordinator chooses a supported language and approves the message. The patient page retrieves that run-scoped approval, plays the committed ElevenLabs asset and can record a separate message acknowledgment. There is no runtime ElevenLabs generation, general chat, SMS integration or Humira audio. Browser decode/playback was checked; native pronunciation and audible physical-phone acceptance are separate.', 'Message acknowledged does not mean the audio was heard, the card was used, or the medicine was taken.')
]),
('Demo tools and frontend evidence', 'docs/handoffs/frontend-audit-fixes.md; docs/claims-audit.md; lib/rxfill.ts; app/(screens)/sim', [
('What is simulated and what really runs?', 'The screens, guarded backend and provider integrations run; patients, pharmacy events and partner fulfillment are simulated.', 'The seed is 13 background cases: 3 needing a fix, 2 waiting and 8 confirmed; Maria and James are separate, for 15 catalog cases. The simulator fires permitted scripted beats. The raw RxFill-shaped panel labels its projection as simulated vocabulary, not a certified wire message. Mock autoplay is not live pharmacy automation. The Relay Board is an audience visualization; its fictional price change is not measured savings.', 'Do not infer dispensing from a paid claim: the workflow’s explicit simulated confirmation is separate.'),
('What frontend work did the team actually finish?', 'Merged repairs address layout, simulator wording, keyboard focus, search feedback, contrast, QR labels and navigation structure.', 'The audit found narrow-screen overflow and an incorrect all-events-fired message when prerequisites were merely blocked. Repairs distinguish loading/blocked/completed states, improve focus return and route focus, add an accessible skip destination and search announcements, and improve QR/table/landmark access. Recorded local verification includes 724 tests, live/mock builds and 57 axe scans. Those fixtures do not prove every production interaction or complete accessibility conformance.', 'Explain the user consequence: a small screen fits, a keyboard user can navigate, and operator status describes the actual state.'),
('How strong is the testing evidence?', 'It includes unit, SQL, browser and hosted-provider checks, each with a different scope.', 'The hosted audit after PR #39 exercised Maria and James, coordinator/message persistence, audio, independent-session reset and live Tiger summaries. Its 62 observations are route/browser/viewport checks, not 62 separate end-to-end scenarios. Frontend repairs had 44 checks each in Chromium and Firefox; WebKit’s one skip-link failure was fixed and rechecked. Later merged code still needs targeted deployed acceptance. Tests were not rerun merely to generate this PDF.', 'Keep code presence, recorded tests, deployed observations and physical-device evidence as four separate claims.')
]),
('Production, failure and measurement', 'docs/claims-audit.md; docs/handoffs/vinh-phase2-live.md; docs/who-sees-what.md; master business evidence pages', [
('What happens when a provider or network fails?', 'The system exposes the missing capability and preserves the committed workflow where possible.', 'Gemini returns null safely. Analytics replay failure does not undo the command or block the independent notification attempt; a later summary request can replay retained history. Unavailable analytics is not reported as a zero success. A failed watch attempt does not prove physical delivery. Voice falls back to the button path. In the presentation, use the prepared phone or a clearly labeled replay if needed, and never silently describe mock output as a live provider result.', 'A successful core command and a successful downstream notification are separate facts.'),
('What is required before real deployment at scale?', 'Real data agreements, identity/authorization and operational acceptance are still substantial work.', 'The prototype has a single shared demo environment and fixed fictional identities. A production plan would need actual pharmacy/network integration and matching, tenant/role boundaries, appropriate data handling and retention, partner contracts, monitoring and support, load/latency evaluation and a defined recovery process. The active-run lock and 1.5-second polling are reasonable demo choices but are not evidence of population-scale capacity. TestFlight source also needs Mac signing/build/install acceptance.', 'Explain the next engineering work honestly; do not equate a deployed demo with production readiness.'),
('How would a pilot prove useful and profitable?', 'Measure net staff effort and meaningful workflow outcomes, then test whether a buyer will pay more than delivery costs.', 'Define eligible cases and a comparison/baseline first. Track staff minutes and touches, unresolved-case age, independently observed fills and time to fill, failures and manual overrides. Separate missing data from confirmed non-fill. Include integration, support, infrastructure and provider costs. The guide’s 200 cases × 5 minutes = 16.7 hours and $583 at $35/hour is an illustrative capacity-value scenario, not observed savings or cash recovered.', 'A pilot should test the assumptions that drive the business model, not just generate attractive dashboard counts.')
])]

ROLE = {
'Vinh': [
('Vinh: defending the product and business', 'Master evidence pages 8–13 and 35; team-reported representative feedback', [
('Why did the Impiricus representative call this a major problem?', 'The reported feedback recognizes the importance of the prescription-to-access gap.', 'A successfully transmitted order does not tell the care team that the patient obtained the medicine. A barrier creates follow-up work across people and systems. FirstDose proposes an accountable coordinator workflow around that gap. Surescripts’ 27% statistic and AMA administrative-work data support the broader problem, with the denominators preserved in the master. A conversation with one representative is qualitative feedback, not a formal endorsement, partnership, ranking or proof of our impact.', 'Pitch line: We connect a reported barrier to an accountable next step and a later pharmacy fill signal.'),
('Isn’t this already solved by Surescripts, Spark or an EHR?', 'Existing abandonment and engagement products exist; our proposed contribution is the coordinator workflow around action and follow-up.', 'Do not claim nobody can see a fill or that a competitor cannot report a reason without evidence. Surescripts markets first-fill monitoring and outreach support. Impiricus describes Spark triggers and Ascend resource access. We need partner feedback on overlap and integration. Our demo makes a concrete workflow reviewable: owner, rule-constrained task, patient resource, separate confirmation and reporting. Real differentiation must be validated with the people who would use and buy it.', 'Answer the overlap directly; explain the proposed workflow rather than inventing an empty market.'),
('Who pays, what is the product, and can it make money?', 'It is a recurring coordinator workflow; a practice or platform/access program is a proposed buyer, with pricing unvalidated.', 'A license or a fee for qualifying confirmed cases is a hypothesis. The illustration uses $50 revenue and $20 variable cost per qualifying case: $30 contribution, covering $25,000 fixed costs at 834 cases. At 1,000 cases, that leaves $5,000 before tax/financing under those assumptions. Costs must include failures and non-billable work; acquisition, onboarding and legal/contract terms also matter. We have no customer contract or proof that labor savings alone supports that fee.', 'If pressed for traction: report the representative conversation and actual demo evidence; do not call either revenue.')
]),
('Vinh: defending the engineering and demo', 'lib/server/commands.ts; lib/realtime.ts; notification-worker.ts; master pages 4–6', [
('What was the hardest engineering problem?', 'Keeping multiple views consistent while accepting only valid actions and separating acknowledgment from fill evidence.', 'The implementation combines a deterministic planner with atomic database commits, unique event identities, active run/revision checks and stale-response rejection. Coordinator approval and messages have their own run-scoped persistence. Notifications and analytics follow committed work rather than deciding whether a command occurred. Describe these as team contributions; your lane is the workflow, router/schema, simulator/API, synchronization and notification/optional voice backend.', 'Good example: a patient tap cannot skip ahead to the independent pharmacy confirmation.'),
('What should I show if a judge challenges whether it is real?', 'Show one observable state transition across independent signed-in screens, with the source and simulation labels visible.', 'Have the doctor hand off, show the coordinator task, send the resource, then let the patient acknowledge. Pause to prove that fill remains pending. Have the agreed operator fire the separate simulated pharmacy event; show the later state. Show the actual Tiger source label if analytics is available, and acknowledge that the pharmacy input is synthetic. Physical watch receipt must be visible or reported as absent. Avoid opening private environment files or credentials during questions.', 'The strongest proof is the distinction between the tap and the separate confirmation, not the length of the stack list.'),
('Which questions should I hand to Minh or Khadim?', 'Lead build, workflow, polling and watch questions. Khadim takes buyer, market and partner fit; Minh takes AI and labels. Add one sentence if Minh needs support.', 'Use a concrete handoff: Minh can explain how the source text and analytics result are verified. Khadim can explain who would buy the workflow and what remains a pricing hypothesis. Know the shared limits yourself: two verified drugs, fixed synthetic identities, no real partner fulfillment, local contact marks, optional voice limitations and physical acceptance remaining. You do not need to guess an implementation detail to appear prepared; point to the relevant source and teammate.', 'If you do not know: We have not verified that yet; here is what we did verify and the next check.')
])],
'Minh': [
('Minh: explaining narrow, verifiable AI', 'scripts/labels; lib/server/classify.ts; lib/server/classifier; lib/server/commands.ts', [
('Why should anyone trust the label or model output?', 'They are different trust problems: labels use a source-verification contract; model output is treated as a constrained interpretation.', 'Do not merge the claims. The label pipeline checks cached source-derived text and identity evidence. Gemini returns only a permitted reason or null and never writes the patient narrative or chooses treatment. A model output passing the parser means it has the allowed format, not that the reason is factually correct. Demonstrate the altered-text failure for the label and safe null behavior for the classifier as separate tests.', 'ELI5: a verified photocopy and a reader’s interpretation are not the same kind of evidence.'),
('Is the AI robust to prompt injection or strange notes?', 'The narrow output contract and deterministic router limit what an untrusted note can influence; they do not establish perfect robustness.', 'The source note is untrusted input. Length/blank checks, exact output parsing and allowlisted reason values reject many invalid replies. The live planner validates the command batch first and accepts the result only through server context. Injection-shaped fixtures were exercised, but a single fixture is not a broad security evaluation. A malicious or confusing note could still lead to a valid but incorrect category; real data requires adversarial and labeled quality evaluation.', 'Never call enum validation a proof of semantic accuracy.'),
('Which model worked, and what do the timings prove?', 'Recorded production-classifier smoke passed with gemini-3.1-flash-lite; timings are individual observations.', 'The handoff records an earlier gemini-3.8-flash price attempt missing the four-second deadline. A flash-lite run passed the four fixtures; later price/unreachable cases returned expected enums while null cases hit the deadline and safely returned null. That means null is intentionally ambiguous between unknown, rejection and provider failure. Do not turn four cases into an accuracy percentage or quote the fastest request as the expected production latency.', 'The important behavior under failure is that no scripted reason is silently restored.')
]),
('Minh: defending metrics and provenance', 'lib/server/analytics/summary.ts; analytics/store.ts; replay-followup.ts; docs/handoffs/vinh-phase2-live.md', [
('How do you know the SQL and displayed metrics agree?', 'The project compares stored/query results with a pure summary oracle and checks replay behavior.', 'The pure function is an independently inspectable implementation of the metric contract: deduplicate event identities, isolate the run, establish prescription time, select a valid fill and compute the median. SQL/oracle checks cover edge cases and recorded hosted runs. Concurrent retry evidence checks stable counts. Explain which layer each test exercises; local PostgreSQL checks do not alone prove hosted Timescale setup or a rendered browser result.', 'The recorded hosted audit supplies the separate browser-level evidence for the live summary.'),
('What are the awkward cases in time-to-fill?', 'Duplicate events, early fills, equal timestamps, even-number medians and missing evidence all need explicit rules.', 'A fill before prescription does not qualify; it must not hide a later valid fill. Equal-time dispensing can qualify because prescriptions are established before fill selection. A case counts once using its earliest qualifying confirmation. The pure summary rounds the median to whole seconds; an even cohort uses the two middle values. Empty cohorts return null, not zero seconds. A confirmed fill still does not establish ingestion or treatment response.', 'When questioned, define the cohort and the event timestamps before interpreting the number.'),
('What can I say about privacy and the analytics export?', 'The projector minimizes fields and uses a keyed per-run case hash; that is pseudonymization and a limited data contract.', 'Do not describe it as anonymous or HIPAA-certified. Check what leaves each boundary: Tiger metric fields, Gemini note, ntfy alert text and optional xAI audio differ. Preserve the HMAC key for retained runs because a changed hash conflicts with immutable prior projections. The current shared demo session does not enforce a distinct pharma-only viewer. A production buyer interface needs its own authorization and disclosure controls.', 'Lead with exactly what is excluded from the Tiger projection, then acknowledge the wider system boundary.')
])]
}

ADVANCED = [
('Label identity and the verification chain', 'lib/server/labels/identity.ts; lib/server/labels/extract.ts; scripts/labels/verify.ts', [
('How do you avoid attaching correct text to the wrong product?', 'Check the product identity and source metadata as well as the copied narrative.', 'The identity selector treats saved RxNorm responses as untrusted and requires one branded product matching brand, ingredient, strength and form. It rejects ambiguous results, packs and substitution of a generic concept for the expected branded product. Token-boundary matching avoids treating 130 mg as 30 mg. The saved Otezla evidence uses RxCUI 1492746 for apremilast 30 mg oral tablet. SPL set/document/version/effective-time checks must agree with provenance and the published catalog.', 'A correct paragraph attached to the wrong strength still fails the intended verification contract.'),
('Which parts of SPL are extracted, and how?', 'Four selected section types are supported, with deterministic narrative extraction and no model paraphrasing.', 'The targets are boxed warning, indications, warnings/precautions and dosage/administration, identified by their section codes. An absent boxed warning can be null. The extractor preserves supported nested narrative in document order with explicit whitespace/newline/table rules, decodes entities once and rejects unsupported narrative rather than silently dropping it. Verification compares the original XML hash, method, section order/titles, exact extracted text and per-section hashes. It is not a claim that the whole SPL appears on the card.', 'Byte-exact refers to the project’s extracted-text contract, not identical visual rendering of XML.'),
('What prevents the build from verifying a newly rewritten answer?', 'The prebuild verifier checks existing saved and published artifacts rather than rebuilding the object under test.', 'The source XML, provenance, RxNorm evidence, label JSON and verification receipt are checked together; published fixture/catalog values must match. The receipt links their hashes. Runtime compares fixed known drug IDs and bundled objects with the receipt; user input never becomes a filesystem path. Unknown drugs return null/HTTP 404. A known artifact failing receipt verification is marked unverified and the route returns 503. This avoids depending on a live DailyMed request during the demo, while leaving source refresh/change monitoring as future operational work.', 'Caching improves demo repeatability; it does not establish that the cached version will always be the latest.')
]),
('Classifier contract and a precise fallback', 'lib/server/classifier/gemini.ts; lib/server/classifier/parse.ts; lib/server/classify.ts', [
('What are the actual reason categories?', 'Six business reasons are allowed; UNKNOWN becomes null.', 'The categories are DECLINED_AT_PRICE, COPAY_NOT_APPLIED, UNABLE_TO_REACH, PA_REQUIRED, NOT_COVERED and NOT_PICKED_UP_48H. The transport requests structured JSON with one reason key, temperature zero and no thinking budget. The parser rejects prose, markdown fences, arrays, extra fields, malformed JSON and invented categories. The model cannot supply a new fix or instruction through this output contract. These settings improve constraint, not guaranteed semantic correctness.', 'Example of an allowed shape: {"reason":"UNABLE_TO_REACH"}. That shape alone does not prove the note was interpreted correctly.'),
('Where does the note come from, and what about retries?', 'Only the supported existing pharmacy/hub evidence note is classified after full transition validation.', 'For the two live classification beats, the executor selects the associated source event note from the validated history/plan. The browser cannot send an arbitrary trusted reason override. Results are cached by source identity and note during database revision retries, so contention does not repeatedly call the model. Once a classification event is committed, retrying the command does not reinterpret it. Offline planner calls can still use scripted reasons, so always state the active mode.', 'The live null fallback must not quietly become a scripted confident answer.'),
('Why collapse uncertainty and failure into the same null?', 'The current contract chooses one safe administrative fallback instead of requiring downstream code to trust uncertain distinctions.', 'Missing configuration, rejected output, provider errors, UNKNOWN and timeout all yield null. The case can be handled through access support without a reason alert. This reduces failure modes in the demo, but limits observability: a null fixture does not prove the provider explicitly answered UNKNOWN. Production operations might need separate internal diagnostics and a human review workflow. Those would need design and privacy review rather than being assumed present.', 'The presentation should say unclassified, not claim that the AI confidently discovered there was no barrier.')
]),
('Analytics ledger, SQL and interpretation', 'scripts/analytics/schema.sql; lib/server/analytics/store.ts; lib/server/analytics/summary.ts', [
('Why a separate event-key table beside the hypertable?', 'Event identity must stay unique even if someone changes its timestamp.', 'The ordinary event_keys table keys run_id plus script_id and stores a payload checksum. The time-partitioned fill_events hypertable includes time in its primary key. A sorted transactional batch inserts a new ledger identity before a metric; on an existing identity it compares the immutable payload checksum. Changed content is a conflict and rolls back. Original timestamps are preserved during replay. The content checksum is SHA-256 over ordered fields; it is different from the keyed HMAC case identity.', 'The ledger prevents the same event from reappearing as a second row merely because its time changed.'),
('Can you explain the median without jargon?', 'Sort qualifying fill durations and take the middle value, or average the middle two.', 'For a purely mathematical example, durations 30, 60, 90 and 120 seconds have a median of 75 seconds. The implementation rounds the result to whole seconds and returns null when no qualifying fills exist. SQL uses PERCENTILE_CONT(0.5) and is checked against a pure TypeScript oracle. Equal-time fills can count; pre-prescription fills do not. The confirmed-only cohort excludes unresolved cases, so present unresolved counts/ages separately in a real pilot.', 'Do not use a falling median by itself to prove better access; the cohort and missing-data rules matter.'),
('Why two databases, and is that faster?', 'The implementation separates authoritative workflow history from a minimized analytics projection; speed superiority is not established.', 'Supabase owns accepted workflow events and Tiger serves derived metrics. Independent replay means analytics trouble does not undo a successful workflow action. The projection also makes exported fields explicit. A single database could compute these metrics; no benchmark demonstrates that two databases are necessary, cheaper or faster. Current reads are direct SQL, not continuous aggregates, and checkpoint checking is not one distributed ACID transaction across both stores.', 'Explain the responsibilities and tradeoff, not an unmeasured performance claim.')
])]

# Preserve the full business explanations for every reader; change Q&A ownership.
ROLE['Vinh'][0]=(ROLE['Vinh'][0][0].replace('Vinh:', 'Business backup (Khadim leads):'),*ROLE['Vinh'][0][1:])
ROLE['Khadim']=[
    ('Khadim: product, buyer and partner fit',*ROLE['Vinh'][0][1:]),
    ('Khadim: presenting the evidence honestly', 'pitch_script.json; docs/minh-signoff-5.1.md; master pages 44–45', [
        ('Why change the supplied script?', 'Preserve the story while making every claim defensible against the current build.', 'Screens synchronize by polling. James’s latest hub note means unable to reach, even though his earlier pharmacy rejection is prior authorization. Only selected metrics reach Tiger. Staff seats and partner fulfillment are proposed integration work. These corrections prevent an impressive demonstration from promising a product contract or integration that does not exist.', 'Keep the confident main story and know the precise boundary when asked.'),
        ('Why not say 467,000 customers?', 'Medical assistants are a workforce context, not a verified count of access coordinators or potential customers.', 'The current BLS page checked for this revision reports 833,900 medical-assistant jobs in 2025. The supplied 467,000 figure appears to be 833,900 multiplied by 56 percent, but that office share was not independently confirmed in the fetched page. Even a correct employment estimate would not prove role fit, budget ownership or willingness to pay.', 'Use the stronger directly supported AMA workload facts in the spoken pitch.'),
        ('What does the representative feedback prove?', 'It is qualitative evidence that one industry conversation recognized the problem.', 'Attribute the feedback to the team’s conversation. Do not imply a written company endorsement, an industry ranking, a commercial agreement or proven impact. Ask the partner to validate the workflow owner, integration overlap, pilot access and who would fund a defined outcome. Keep payment per qualifying confirmed fill a proposed experiment, with contract and attribution terms to be established.', 'Hand implementation detail to Vinh and AI/label detail to Minh.')
    ])
]
