"""Source-backed personal study content; speaking cues are deliberately brief."""

PAGES = [
('Your demo: one loop, five jobs', 'Vinh / Demo, backend, AI, labels and analytics • September 27, 2026', [
('YOUR JOB', 'Show one complete case, explain why the state changes, and prove that a click is not a fill. You can cover Minh’s AI/labels/analytics material using this guide. Khadim still owns the opening and business close.'),
('THE PRODUCT', 'FirstDose is a prototype for a coordinator workflow inside a DocUpdate/Ascend concept. It connects a reported prescription barrier to an accountable staff action and then waits for independent pharmacy confirmation. It does not itself dispense medicine or know whether a dose was taken.'),
('REMEMBER THIS', 'Gemini reads. Rules route. Humans approve. Supabase remembers. Tiger measures.'),
('HOW TO USE THIS PDF', 'Page 3 is your short spoken demo. The remaining pages are preparation and judge answers, not extra narration to squeeze into the pitch. Read the purple SAY lines aloud; learn the backend explanations so you can expand when asked.'),
('EVIDENCE', 'Checked against main 015c342, your pasted Devpost story, public track pages and your confirmed selections: Oracle of the Deep, Impiricus and SpaceXAI. The linked YouTube upload is included as your presentation reference; its playback/transcript was not independently reviewed. MLH selections were not supplied.')
]),
('Your short spoken demo', 'Target about 2–3 minutes with clicks; rehearse actual device latency.', [
('QUEUE → DOCTOR', '“This is the coordinator’s queue: three need a fix, two are waiting, eight are filled. Our Next.js and React screens share workflow state in Supabase. Maria’s fictional prescription shows a label verified against saved DailyMed source.”'),
('BARRIER → HANDOFF', '“Our operator supplies a simulated pharmacy update. Gemini reads the note and identifies declined at price. It only classifies the reason. A deterministic rule chooses the action. The doctor gets an alert. I can tap the handoff, or use Grok to prepare the request and then confirm it. Both use the same approved coordinator workflow.”'),
('RESOURCE → PATIENT', '“The coordinator sends a savings-card stand-in. The optional English or Spanish message uses pre-generated ElevenLabs audio. Now tap Use at pharmacy. That records acknowledgment; it does not confirm a fill.”'),
('CONFIRMATION → WATCH', '“Now we send the separate simulated pharmacy confirmation. The shared screens update, and the notification service sends the confirmation alert. We verify the watch actually receives it.”'),
('JAMES / YOU COVER MINH', '“James’s later hub note says he could not be reached. Gemini returns that reason, or leaves it unknown if classification fails. His rule-selected action is access support. Sending that request still leaves him unfilled.”'),
('MARKET ACCESS → HAND BACK', '“Tiger Data receives selected, minimized events and measures confirmed first fills and time to first fill. Eight seeded fills plus Maria gives nine; James adds none. These are demo outcomes. Our AI and analytics support Oracle; staff handoff supports Impiricus. Grok adds a voice request that still needs confirmation. Khadim will close.”'),
('CUT RULE', 'If time is tight, keep Maria’s acknowledgment-versus-confirmation pause. Cut optional patient audio, then the James interaction. For SpaceXAI judging, preserve the rehearsed voice proof; for a general short pass, offer voice during questions. Mention the full stack in one sentence only if asked: Next.js, React, TypeScript, Supabase Postgres, Gemini, Tiger Data, Grok, ElevenLabs and ntfy, hosted on Vercel.')
]),
('Set the table before presenting', 'The simulator represents outside systems; the doctor still signs in the doctor UI.', [
('DEVICES', 'Doctor phone: /doctor. Patient phone: /patient/rx_001. Audience laptop: /coordinator, then /board or /access. Operator window: /sim. Use https://firstdose.vercel.app on every device, authenticate beforehand, and verify Live data on /sim.'),
('RESET / SEED', 'Pause other users. Reset → Confirm reset immediately → wait for 0 committed events → Seed before any prescription. Expect the 3 / 2 / 8 queue. A nonempty run can reject Seed with invalid_transition. A page refresh does not reset the shared run.'),
('APPROVE THE COORDINATOR', 'Coordinator Prescribers → Request Dr. Nadia Okafor approval. Doctor Profile → Review request → Approve. Verify Linked. Reset clears current links/messages, so approve again after reset. This is a demo approval model, not verified professional identity.'),
('OPERATOR SEQUENCE', 'Maria: doctor Sign and send → ev_04 → ev_05 → doctor handoff → coordinator Re-send copay card → patient Use at pharmacy → ev_11. James, after Maria: doctor Sign and send → ev_16 → ev_17 → ev_18 → handoff → Connect to access support. Wait for each result.'),
('WHY /SIM EXISTS', 'It supplies controlled fictional pharmacy/hub inputs where a real external integration would sit. Clicking ev_11 is not evidence that a real pharmacy dispensed anything. The backend still checks prerequisites and commits the resulting workflow consistently.')
]),
('Step 1: prescribe and verify the label', 'Screen: doctor New Rx → Maria / Otezla → Sign and send.', [
('SAY', '“The label comes from a verified saved source. Signing the order records the beginning of the workflow; it does not establish a fill.”'),
('BACKEND', 'POST /api/rx validates the prepared demo prescription and commits its event through the workflow server. GET /api/label/[drug_id] serves a fixed allowlist of verified bundled label artifacts. This demo does not transmit a real prescription to a pharmacy.'),
('WHAT RXNORM DOES', 'RxNorm/RxNav supplies normalized drug identity; DailyMed supplies the Structured Product Label, or SPL. The saved identity and label artifacts are checked together. These are reference sources, not generative models.'),
('WHAT VERIFICATION MEANS', 'Prebuild verifies both Otezla and Humira. Checks cover product identity, source/version/hash, deterministic extraction, selected section order/text/hashes, a verification receipt and agreement with the published fixture. Humira also checks concentration, volume and KIT presentation.'),
('ELI5', 'The label is like a checked photocopy of selected pages. The AI does not rewrite it. The checker verifies where those pages came from and whether their saved contents changed.'),
('IF ASKED', 'We render four selected sections, not the entire label’s original visual layout. Runtime uses cached verified artifacts, not a fresh DailyMed request. Unknown drug returns 404; known but unverified artifact returns 503. This verification is not FDA approval of FirstDose.')
]),
('Step 2: classify the pharmacy note', 'Operator: Maria ev_04, then ev_05. Show the actual result.', [
('SAY', '“Gemini converts the pharmacy’s short note into one allowed reason. It does not select the medicine, write the label or choose the fix.”'),
('INPUT → OUTPUT', 'The supported fictional note is limited to 140 Unicode code points. The Gemini API is called server-side through @google/genai with a constrained JSON schema. Expected shape: {"reason":"DECLINED_AT_PRICE"}. The six codes are DECLINED_AT_PRICE, COPAY_NOT_APPLIED, UNABLE_TO_REACH, PA_REQUIRED, NOT_COVERED and NOT_PICKED_UP_48H. UNKNOWN is also allowed; extra keys and malformed values are rejected.'),
('MODEL / FAILURE BEHAVIOR', 'GEMINI_MODEL selects the model. The recorded successful integration pin is gemini-3.1-flash-lite; that is not a fresh check of the deployed environment. Temperature is 0 and the deadline is 4 seconds. UNKNOWN, malformed output, missing config, provider failure and timeout become null.'),
('IMPORTANT PRECISION', 'There is no numeric confidence score, threshold or automatic backup-model switch. UNKNOWN or errors become null; the case stays unclassified and no reason-triggered alert is created. A valid enum can still be wrong about the note. Schema validation is not an accuracy guarantee.'),
('ELI5', 'Gemini is the person who sorts a messy sticky note into a labeled tray. If it cannot produce an acceptable label, the note stays for a human. It is not allowed to invent a new tray or complete the task itself.'),
('DEMO RECOVERY', 'If classification fails, do not read the scripted reason as though it appeared. Explain the unknown state and use the available Patient Details/access-support path. A null result does not silently restore a prerecorded reason or its alert.')
]),
('Step 3: the rule and human handoff', 'Doctor: Send to my coordinator. Coordinator: open Maria’s case.', [
('SAY', '“The model names the barrier. A deterministic rule picks one administrative next step, and a person approves the action.”'),
('RULE ORDER', 'The router uses the reason plus recorded insurance/eligibility. Card routing also requires copayCardEligible to be true; bridge routing requires bridgeSampleEligible to be true. Government coverage is checked first and routes to access support; it never receives RESEND_COPAY_CARD in this prototype. Eligible commercial price/card problems can route to Re-send copay card. Prior authorization and noncoverage route to access support.'),
('THE THIRD OPTION', 'The rule set also has Request bridge sample, including a configured commercial unable-to-reach path. That is a prototype administrative request and partner stand-in, not permission to dispense a sample or a general clinical recommendation.'),
('HANDOFF BACKEND', 'POST /api/handoff checks the case, run, prerequisites and coordinator link. Coordinator approval is recorded through /api/coordinator. A successful handoff changes task ownership; it does not send a real external partner request or imply successful patient contact.'),
('ELI5', 'AI reads the envelope. A checklist decides which desk it belongs on. The doctor hands it to a named coworker. That coworker decides to send the prepared resource.'),
('IF ASKED WHY NOT ALL AI', 'The rule is inspectable and repeatable, and eligibility gates remain outside a probabilistic model. Human review catches context the prototype does not understand. A deterministic rule can also be wrong or incomplete; production rules need domain validation.')
]),
('Step 4: resource and spoken message', 'Coordinator: Re-send copay card. Patient: card appears.', [
('SAY', '“The coordinator sends a prepared resource. The patient gets the card on their page; optional English or Spanish audio makes the approved message easier to consume.”'),
('BACKEND', 'POST /api/fix accepts only the permitted administrative action for the current case. The shared event history drives the patient page. Wallet, Concierge, QPharma and Medvantx are proposed integration destinations shown as stand-ins; no real benefit enrollment or sample fulfillment occurs.'),
('ELEVENLABS IN THE APP', 'scripts/tts.mjs uses the ElevenLabs text-to-speech API with eleven_multilingual_v2 to generate the English and Spanish Otezla message MP3s ahead of time. Committed files live in public/audio. The application does not call ElevenLabs at runtime.'),
('CLICK PATH', 'After the eligible resend action, the coordinator can select Español and Approve and send a patient message. The patient taps Play message. The message text comes from approved templates; the app does not freely translate or generate clinical advice.'),
('BOUNDARIES', 'Message acknowledgment is separate from Use at pharmacy. Neither is a fill. The app has no SMS, no general voice chatbot, no audio autoplay and no Humira message audio. Text remains available if sound fails.'),
('ELI5', 'Think of a prerecorded instruction card with a play button. The coordinator chooses when to hand it over. The speaker is reading the prepared message, not inventing advice.')
]),
('Step 5: acknowledgment, then proof', 'Pause visibly between the patient tap and the operator’s pharmacy event.', [
('SAY', '“Her tap is an acknowledgment. We still wait for the pharmacy. Now the separate pharmacy confirmation arrives, and only then does the case become Fill confirmed.”'),
('TWO DIFFERENT COMMANDS', 'Patient Use at pharmacy calls POST /api/patient/use. It records resource acknowledgment. Separately, the operator fires Maria ev_11 through POST /api/sim/fire, representing a pharmacy Claim run with status Dispensed. In this scripted sequence that event is gated by the earlier acknowledgment.'),
('WHY THE PAUSE MATTERS', 'A button tap shows interaction, not dispensing. A sent support request shows work, not resolution. A pharmacy confirmation is the prototype’s fill evidence; even that does not prove the patient took a dose. Nine demo fills are not nine clinically improved patients.'),
('BACKEND RESULT', 'The accepted confirmation is committed to Supabase. The doctor, coordinator, patient and board read the new shared history. After commit, notifications and analytics replay are scheduled separately; they are not prerequisites for durable workflow truth.'),
('ELI5', 'Opening a delivery message is not receiving the package. The delivery confirmation comes from the delivery system. And receiving the package still does not prove you used what was inside.'),
('CHECKPOINT', 'Show the pending message first. Then confirm the case changes. Keep the same run for James and Market Access; do not reset between cases.')
]),
('The watch is an output, not the database', 'Show actual receipt; an API response is not the wrist buzzing.', [
('SAY', '“We send a reason alert and a later fill-confirmation alert. The workflow is stored first; notification delivery happens afterward.”'),
('PATH', 'Committed workflow event → notification outbox → server notification worker → HTTPS POST to ntfy → paired phone notification → watch mirroring. Historical Garmin Forerunner 55 receipt is recorded, and you reported phone/watch success in rehearsal.'),
('DELIVERY GUARDS', 'The intent is written with the accepted workflow batch. Workers atomically claim pending notifications to avoid normal concurrent duplicate sends. Messages use bounded template text; ntfy requests have a 5-second timeout. At most two sends are attempted per worker invocation.'),
('HONEST RELIABILITY', 'This is not exactly-once physical delivery. Claimed or uncertain sends are not automatically resent. A request already in flight may finish after reset. Provider acceptance does not prove phone delivery, watch pairing, permissions or wrist receipt.'),
('IF THE WATCH FAILS', 'Show the actual doctor-screen alert and say that wrist delivery did not arrive. Do not wave a browser watch graphic as proof of physical delivery. Keeping the notification separate means a missing buzz does not erase the stored case.'),
('ELI5', 'The database is the notebook. The watch is the doorbell. A broken doorbell should not erase what was written in the notebook.')
]),
('Step 6: James and your AI explanation', 'Doctor signs James / Humira. Operator: ev_16 → ev_17 → ev_18.', [
('SAY / MINH’S PART, IN YOUR WORDS', '“James’s first pharmacy event is a prior-authorization rejection. His later hub note says they could not reach him. Gemini classifies that later note as unable to reach. A rule sends this case to access support. A sent support request is not a confirmed fill.”'),
('WHY HIS REASON IS NOT JUST PA', 'ev_16 records reject code 75, prior authorization required. ev_17 supplies the later failed-contact hub note. ev_18 classifies that note. The expected current reason is UNABLE_TO_REACH. Read the actual classification instead of assuming the original PA is the model output.'),
('ACTION', 'Doctor Send to my coordinator → coordinator James → Connect to access support. The doctor can still show stuck/unfilled and “With your coordinator.” That is correct. This sequence does not contain a James dispensing confirmation.'),
('WHY THE SECOND CASE HELPS', 'Maria proves a completed loop. James proves that an incomplete case remains incomplete even after a helpful action. It demonstrates workflow honesty and a different barrier, not a second successful recovery.'),
('IF ASKED ABOUT AI', '“AI reads the note. A rule picks the fix. A human taps send.” Add: invalid or unavailable classification becomes unknown; there is no hidden confidence threshold and no model-generated patient/label copy.'),
('OPERATOR TIP', 'Do James after Maria, so his alert does not interrupt Maria’s barrier/confirmation story. Optional Grok voice can be demonstrated separately if already rehearsed; the tap path is sufficient for the core loop.')
]),
('How three devices share one truth', 'Next.js commands + Supabase transaction + authenticated polling.', [
('SAY', '“Every device sends commands to the same server. The server checks the current run and revision before accepting a change. Other devices then read the accepted state.”'),
('WRITE PATH', 'React UI → Next.js API route → workflow planner → Supabase REST RPC. The planner validates prerequisites and builds an event batch. SQL locks the active run, checks expected run/revision, and commits the full batch plus notification intents atomically.'),
('RUN / REVISION', 'A run identifies this rehearsal; a revision identifies the accepted version within it. Reset creates a new run and retains old history. Stale commands cannot modify the fresh run. Revision conflicts re-read and re-plan, with a bounded retry count of three.'),
('IDEMPOTENCY', 'A run/script identity prevents duplicate event insertion. Repeating an accepted operation does not create a second identical event. This addresses double taps and concurrent requests; it is not a blanket guarantee about every external service.'),
('READ PATH', 'GET /api/events returns the current snapshot. Browser clients normally poll every 1.5 seconds, use ETags/304 for unchanged data, refresh after commands and reject stale responses. The file is named realtime.ts, but the live transport is polling, not Supabase Realtime, WebSockets or SSE.'),
('ELI5', 'Run is the notebook’s name. Revision is the page number. Before adding a line, the server checks you are holding the current notebook and page. Every screen checks the notebook again soon afterward.')
]),
('Step 7: what Tiger Data actually does', 'Market Access /access → confirm the source badge before attributing the metrics.', [
('SAY', '“Supabase stores the operational history. We project selected committed events into Tiger Data, which calculates first-fill counts and elapsed time. The dashboard shows aggregate results.”'),
('PROJECTION', 'Only authoritative prescription, allowed reason-classification and independent dispensing events become metrics. Each row contains run ID, script ID, a keyed HMAC case hash, timestamp, kind and optional allowed reason. No patient name, raw case ID, note, drug, insurance, price or wrist text is copied.'),
('STORAGE / REPLAY', 'Tiger Data uses a TimescaleDB hypertable accessed with the pg PostgreSQL driver. Direct SQL computes summaries; this implementation does not use a continuous aggregate. Replaying the same identity and payload is a no-op. Changed content under the same identity conflicts and rolls back.'),
('CATCH-UP / FRESHNESS', 'Next.js after() schedules replay after accepted commands. Summary reads also replay retained committed history to catch up. Run/revision checks and response checkpoints prevent an older run’s metrics from replacing the current view. Analytics failure does not roll back the workflow.'),
('DATA BOUNDARY', 'HMAC means a keyed fingerprint, useful for connecting a case’s events without its raw ID. The internal metric store is pseudonymous, not guaranteed anonymous. The displayed buyer view is counts only; production identity and privacy controls still need work.'),
('IF TIGER IS UNAVAILABLE', 'Name the source badge shown. A practice-event fallback can keep the display useful, but that is not a successful Tiger query. Do not say every event goes to Tiger: the allowlist intentionally excludes most workflow detail.')
]),
('Read the dashboard correctly', 'Nine is a rehearsal checkpoint, not a product impact statistic.', [
('FIRST FILLS', 'The query counts the earliest qualifying dispensing at or after the earliest prescription, once per case. With the expected seed and only Maria newly confirmed: 8 + 1 = 9. James contributes zero until independent confirmation exists.'),
('TIME TO FIRST FILL', 'For each confirmed case: confirmation timestamp minus prescription timestamp. The dashboard reports the median elapsed time among confirmed cases. Unconfirmed cases do not enter that median. With no confirmed cases, the result is null, not zero.'),
('REASONS', 'The reason tally uses the latest non-null reason per case, including cases later filled. A reason bar is therefore not necessarily the count currently stuck in the coordinator queue.'),
('HOW TO PROVE SAVINGS LATER', 'A pilot would need a baseline/comparison, independently confirmed fills, coordinator minutes per case, unresolved cases and follow-up duration. The fast demo clock and fictional seed cannot show saved hours, better adherence or causal conversion lift.'),
('SAY', '“Maria changes the outcome count; James’s support click does not. The dashboard measures what we can substantiate. In a real pilot we would compare these results with the practice’s previous workflow.”'),
('ELI5', 'The scoreboard counts finished deliveries, not attempted phone calls. The timer only describes deliveries that finished, so you also need to look at the ones still waiting.')
]),
('The stack: explain each tool’s job', 'Use purpose first, name second. Versions reflect the inspected repository.', [
('SCREENS / HOSTING', 'Next.js 16.3.6 provides the web application and server routes. React 19.2.8 renders screens; TypeScript defines contracts; Tailwind 4 and shadcn/Radix supply styling/components. Vercel hosts the web app. QR rendering opens the patient page. The iOS wrapper is a separate client, not a second workflow backend.'),
('WORKFLOW / ANALYTICS', 'Supabase Postgres is the operational store, accessed via server-side REST RPCs such as fd_snapshot, fd_commit, fd_reset and fd_read_run. Tiger Data / TimescaleDB is the smaller analytics store, queried with PostgreSQL SQL through pg.'),
('AI / REFERENCE / DELIVERY', 'Gemini: note classification. xAI Grok: optional speech transcription. RxNorm and DailyMed: saved identity/label verification. ElevenLabs: prerecorded patient-message audio. ntfy: push notifications forwarded through the phone/watch setup.'),
('QUALITY TOOLS', 'Vitest checks behavior; ESLint checks code; PostgreSQL integration checks exercise persistence; browser smoke checks cover UI workflows. The recorded owner sign-off reports 728 tests across 54 files. Those are historical results, not a fresh test run for this PDF.'),
('VIDEO TOOLS', 'Your Devpost describes HyperFrames, GSAP, FFmpeg and whisper.cpp for the edited presentation. These produce the demo video and captions; they do not run the medication workflow. The current local video worktree documents a 2:53 final cut, separate from the main application snapshot.'),
('ONE-SENTENCE ANSWER', '“Next.js and React on Vercel, Supabase for guarded workflow persistence, Gemini for bounded classification, Tiger for minimized outcome analytics, and Grok, ElevenLabs and ntfy for optional voice, message audio and alerts.”')
]),
('API map: commands and reads', 'These are our application endpoints, separate from external provider APIs.', [
('WORKFLOW COMMANDS', 'POST /api/rx records the prepared order. POST /api/handoff transfers follow-up. POST /api/fix records the allowed resource action. POST /api/patient/use records card acknowledgment. GET/POST /api/coordinator handles demo link/assignment state. GET/POST /api/patient/message handles approved message state and acknowledgment.'),
('READS / SESSION', 'GET /api/events returns run/revision/history. GET /api/access/summary?run_id=…&revision=… serves an authenticated, freshness-checked Tiger summary. GET /api/label/[drug_id] serves public verified label content. GET/POST /api/demo-login handles the shared demo session.'),
('OPERATOR / OPTIONAL VOICE', 'POST /api/sim/fire accepts permitted simulated events. POST /api/sim/seed prepares the synthetic background week. POST /api/sim/reset starts a new run. POST /api/voice returns a proposed handoff from speech; it does not perform that handoff.'),
('EXTERNAL CALLS', 'Server → Google Gemini through @google/genai; server → xAI /v1/stt; server → Supabase REST RPC; server → Tiger PostgreSQL; server → ntfy HTTPS. The separately run audio-generation script calls ElevenLabs /v1/text-to-speech/{voice_id}. Saved label/public-data preparation uses NLM/CMS sources.'),
('USEFUL FAILURE WORDS', '401: missing/invalid demo authorization. 409: stale or conflicting state. 503: dependency unavailable. Invalid transitions mean the requested next step does not follow the accepted workflow. Do not retry arbitrary Fire buttons to make an error disappear.'),
('ELI5', 'An API is a service window with a fixed form. The server checks that the form is allowed and current before writing anything. The screen does not get to declare itself filled.')
]),
('Optional Grok: voice still needs consent', 'Use only if rehearsed; skip it when time or microphone reliability is tight.', [
('SAY', '“Grok transcribes the doctor’s request. We match a narrow handoff intent, show it back, and require the doctor to confirm before calling the existing handoff.”'),
('SPACEXAI CLICK PATH', 'Before handing off Maria, tap Tap to speak → say “Send Maria to my coordinator” → tap Listening… tap to stop → check the transcript and Maria/Otezla proposal → tap Send to my coordinator in the proposal. That button is the explicit confirmation; it is not literally labeled Confirm. Complete any approval sheet. Do not perform a duplicate manual handoff first.'),
('IMPLEMENTATION', 'The server calls xAI /v1/stt using grok-voice-transcribe-2.0. It accepts at most 4,000,000 bytes of audio and uses a 20-second provider deadline. Keyterms include the demo’s fictional names/drugs. A narrow whole-utterance grammar resolves a supported case and coordinator handoff.'),
('SAFETY BOUNDARY', 'Transcription is a suggestion. Ambiguous or unsupported speech does not silently pick a patient. The doctor must review and confirm. This is speech-to-text plus a constrained intent resolver, not an autonomous agent or a general clinical assistant.'),
('RESET LIMITATION', 'The main command path is run/revision guarded. Voice has a pre-confirm check, but complete recording-through-approval reset safety is not established: the inspected UI captures run after recording and passes only the case ID onward. Do not claim every voice race is solved.'),
('TRACK CONNECTION', 'SpaceXAI: Make it Legendary is a public prize. The saved organizer brief describes Cursor plus Grok. Explain the actual Grok feature and actual Cursor development work only if you can substantiate both. A watch alert is not Grok evidence.'),
('ELI5', 'Voice fills out the handoff form for you. It does not press the final send button.')
]),
('Real reference data, fictional cases', 'Do not mix public population statistics with the demo’s outcomes.', [
('PROBLEM STATISTIC', 'Surescripts reports 27% of new prescriptions were never dispensed in its January 2026 analysis of e-prescriptions to fill-reporting pharmacies. This motivates the problem; it is not a FirstDose conversion rate or a drug-specific abandonment rate.'),
('CMS / GEORGIA', 'The saved 2024 CMS Part D geography/drug snapshot reports 614 Otezla prescribers and 6,661 claims in Georgia; Humira(CF) Pen has 717 prescribers and 15,295 claims. These are Medicare Part D aggregates, not unique patients, new prescriptions or our addressable paying customers.'),
('FORMULARY CONTEXT', 'In the saved September 2026 Georgia Part D snapshot, coverage is 53.9% for Otezla and 33.6% for Humira(CF) Pen. Among plans that cover each product, the PA shares are 90.2% and 100%. Always name that denominator; these are not patient rejection probabilities.'),
('NADAC', 'Saved effective September 23, 2026: about $90.57 per Otezla tablet and $3,367.41 per Humira(CF) pen. NADAC is pharmacy acquisition-cost context, not the patient’s copay, savings or reimbursement. Maria’s $410 quote is fictional. The file also holds KFF Georgia payer-mix context.'),
('IN THE APP', 'data/reference/public-data.json is a saved snapshot with source/year labels. These are not fresh external API queries on every page visit. Never multiply population statistics by the demo’s outcomes to claim savings.'),
('GRAPH ON THE NEXT PAGE', 'Use the two panels to explain coverage and prior authorization separately. A high PA share among covered plans does not mean the same share of all patients is denied medication.')
]),
('Your three selected tracks', 'Confirmed by you: Oracle of the Deep + Impiricus + SpaceXAI.', [
('ORACLE OF THE DEEP / GENERAL', 'ML/AI entry: show Gemini turning a messy note into a bounded reason, the unknown path, and Tiger’s outcome display. Explain the separation of model, rule and human review. The data visualization distinguishes interaction from independently confirmed outcomes. No claimed accuracy percentage or demonstrated clinical lift.'),
('IMPIRICUS: NEXT HCP ENGAGEMENT TOOL', 'Primary sponsor story: useful physician alerts plus staff ownership after a reported barrier, framed as a proposed DocUpdate/Ascend extension. Show the human handoff and New · FirstDose additions. Existing partner names are stand-ins, not evidence of affiliation or an executed integration.'),
('SPACEXAI / SPONSOR 2', 'Show Grok transcribing a supported doctor handoff, then the proposed case/action and explicit Confirm. Connect it to reduced interaction effort without claiming measured time savings. The saved organizer brief describes Cursor plus Grok: describe actual Cursor development work truthfully. Your selected entry is confirmed; full eligibility/evidence acceptance is not.'),
('ONE-LINE CONNECTION', '“Oracle is our bounded intelligence and outcome analytics. Impiricus is the useful HCP-to-staff workflow. SpaceXAI is the Grok voice request with human confirmation.” For the SpaceXAI judge, include the rehearsed voice path instead of silently cutting it.'),
('MLH IS SEPARATE', 'Public MLH prizes include Gemini API, Tiger Data and ElevenLabs. Your MLH selections were not supplied. If entered, show a real model result, a Tiger-sourced summary or the actual approved patient audio, respectively. This study podcast is preparation, not app-runtime evidence.'),
('CORRECTION TO OLDER GUIDES', 'Your actual form lists Aramco under sponsor tracks and Oracle under general tracks. This user-supplied form and your explicit selections supersede our earlier Aramco-as-general recommendation. Your two chosen sponsors are Impiricus and SpaceXAI.')
]),
('Hard judge questions: architecture', 'Answer the question first; offer the deeper detail only when useful.', [
('WHY TWO DATABASES?', 'Supabase holds the operational workflow; Tiger holds a deliberately smaller analytics projection. That makes the boundary inspectable and supports time-based SQL. It adds replay/freshness complexity; one database could be adequate for a smaller production pilot.'),
('WHY NOT WEBSOCKETS?', 'The shipped prototype uses authenticated polling every 1.5 seconds. It is simple to inspect and adequate for the demo. A production choice would depend on latency, traffic and operations. We do not claim instant delivery or Supabase Realtime.'),
('WHAT IF TWO PEOPLE CLICK?', 'The server checks run/revision under a database lock, commits a batch atomically and deduplicates event identity. Stale writes refresh/re-plan or fail. The UI is not the final authority.'),
('WHAT IF GEMINI IS WRONG?', 'Schema constraints stop invalid shapes, not semantic errors. The reason can remain unknown, actions stay bounded by rules and a human approves. Production needs a labeled evaluation set, per-reason error analysis and operator corrections.'),
('WHAT IF TIGER GOES DOWN?', 'The accepted workflow remains in Supabase. Retained history can replay into Tiger later; the view must disclose a practice-event fallback rather than presenting stale data as current Tiger results.'),
('IS THIS HIPAA-COMPLIANT / ANONYMOUS?', 'We have not established that. The demo uses synthetic patients and a shared demo session. Internal HMAC metrics are pseudonymous. Production requires appropriate identity separation, access controls, agreements, auditing and a reviewed data boundary.')
]),
('Hard judge questions: product and proof', 'Keep your technical answer consistent with Khadim’s business story.', [
('IS THIS A PRODUCT OR JUST A DEMO?', 'It is a working workflow prototype and a proposed product integration. The real parts are screens, guarded persistence, constrained AI, label checks, analytics and notification plumbing. The patients, pharmacy activity and partner fulfillment are simulated.'),
('WHAT ARE YOU SAVING?', 'We aim to reduce unowned follow-up and staff effort. We have not measured hours, dollars, adherence or causal lift. A pilot should measure coordinator minutes per case and confirmed fills against a credible baseline while tracking unresolved cases.'),
('WHO PAYS / IS IT PROFITABLE?', 'The proposed buyer is Market Access, with payment tied to qualifying confirmed first fills. Price, buyer demand, attribution, production costs and commercial feasibility are unvalidated. Profit would require accepted revenue to exceed provider, data-feed, support, integration and operating costs.'),
('WHAT DO YOU ADD TO EXISTING TOOLS?', 'The proposed contribution is connecting a reported barrier to an owned staff action and an explicit outcome check inside the sponsor’s workflow. Surescripts already offers abandonment visibility; do not say nobody can detect unfilled prescriptions.'),
('WHAT WOULD YOU BUILD NEXT?', 'A genuine pharmacy/hub feed and partner adapter, production practice/staff identity, evaluated classification, durable operational monitoring and a practice pilot. The simulator is today’s input adapter, not an external feed certification.'),
('ABOUT THE DEVPOST NUMBERS', 'The roughly 280,000 full-time-equivalent calculation in the public story extrapolates prior-auth workload from separate sources. It is not jobs eliminated, dollars saved, a measured market or a FirstDose result. Your technical demo does not need that calculation.')
]),
('Your 60-second memory drill', 'Say each answer without looking, then check the response.', [
('WHAT IS FIRSTDOSE?', 'A proposed coordinator workflow that turns a reported prescription barrier into an owned administrative action, then waits for independent fill confirmation.'),
('WHAT DOES EACH SYSTEM DO?', 'Gemini reads. Rules route. Humans approve. Supabase remembers. Tiger measures. Grok transcribes. ElevenLabs voices prepared messages. ntfy alerts.'),
('WHY IS JAMES STILL STUCK?', 'Access support was requested, but a pharmacy has not confirmed his fill. The correct unresolved state is a feature of honest accounting.'),
('WHAT DOES NINE MEAN?', 'Eight seeded background fills plus Maria’s independent simulated confirmation. It is not nine measured interventions or nine verified first doses.'),
('WHAT IS REAL / WHAT IS SAVED?', 'The workflow and integrations described in code are real implementation. Patients and external pharmacy events are fictional. Labels, public reference figures and patient audio are saved artifacts; screens poll the live operational store.'),
('YOUR LAST LINE', '“The system separates what someone clicked from what an outside source confirmed. That is why the coordinator can trust the next step and why the dashboard can report a defensible outcome.”')
]),
]

SOURCES = [
('Public FirstDose Devpost story', 'https://devpost.com/software/1446114', 'User-supplied text and public page checked Sep 27. Story is context, not independent proof of every implementation claim.'),
('User-provided presentation video', 'https://www.youtube.com/watch?v=yiAqHZ0ITpQ', 'Linked reference. Page title retrieved; audiovisual playback and exact spoken claims not independently reviewed.'),
('Official HackGT tracks', 'https://hack.gt/', 'Social good: A Marina’s Mission, presented by Aramco.'),
('HackGT Devpost prizes', 'https://hackgt13.devpost.com/', 'Impiricus, SpaceXAI, ElevenLabs, Tiger Data and other public categories. Does not show your selected entries.'),
('MLH HackGT 13 prizes', 'https://www.mlh.com/events/hackgt-13/prizes', 'Includes Gemini, Tiger Data and ElevenLabs.'),
('Surescripts First-Fill Abandonment', 'https://surescripts.com/products/first-fill-abandonment', '27% scope: January 2026 e-prescriptions sent to fill-reporting pharmacies.'),
('Repository at inspected main snapshot', 'https://github.com/khadimswe/firstdose/tree/015c3429a12518ed67753a47db9eaae308e82b13', 'package.json; lib/realtime.ts; lib/server; app/api; mock/reasons.json; scripts/labels; scripts/analytics; scripts/tts.mjs.'),
('Public-data provenance and exact queries', 'https://github.com/khadimswe/firstdose/blob/015c3429a12518ed67753a47db9eaae308e82b13/docs/research/public-data-sources.md', 'Saved CMS, NADAC and KFF values are dated snapshots; not re-fetched for this guide.'),
('Recorded Minh sign-off', 'https://github.com/khadimswe/firstdose/blob/015c3429a12518ed67753a47db9eaae308e82b13/docs/minh-signoff-5.1.md', '728 tests / 54 files and label checks are recorded evidence, not newly run here.'),
]
